export default {
  version: '3.6.3',
  objects: [
    {
      type: 'rect',
      version: '3.6.3',
      left: 513,
      top: 160,
      width: 50,
      height: 50,
      fill: '#8D476B',
      opacity: 0.8
    },
    {
      type: 'circle',
      version: '3.6.3',
      left: 174,
      top: 166,
      width: 100,
      height: 100,
      fill: '#383881',
      opacity: 0.8,
      radius: 50,
      startAngle: 0,
      endAngle: 6.283185307179586
    },
    {
      type: 'triangle',
      version: '3.6.3',
      left: 330,
      top: 242,
      width: 50,
      height: 50,
      fill: '#C8EFF0',
      opacity: 0.8
    },
    {
      type: 'line',
      version: '3.6.3',
      left: 328,
      top: 300,
      width: 150,
      height: 100,
      stroke: '#98D727',
      x1: -75,
      x2: 75,
      y1: -50,
      y2: 50
    },
    // {
    //   type: 'polygon',
    //   version: '3.6.3',
    //   left: 44,
    //   top: 257,
    //   width: 385,
    //   height: 245,
    //   fill: '#6AEFB4',
    //   points: [{ x: 185, y: 0 },
    //     { x: 250, y: 100 },
    //     { x: 385, y: 170 },
    //     { x: 0, y: 245 }]
    // },
    {
      type: 'textbox',
      version: '3.6.3',
      lockScalingFlip: true,
      lockRotation: true,
      left: 10,
      top: 10,
      width: 500,
      height: 75.03,
      fill: 'white',
      angle: 0,
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ',
      fontSize: 14,
      fontWeight: '',
      fontFamily: 'helvetica',
      minWidth: 20,
      splitByGrapheme: false,
      styles: {}
    }
    // {
    //   type: 'i-text',
    //   version: '3.6.3',
    //   left: 348,
    //   top: 326,
    //   width: 598.13,
    //   height: 150.06,
    //   fill: '#D15803',
    //   scaleX: 0.5,
    //   scaleY: 0.5,
    //   angle: 3,
    //   text: 'Lorem ipsum dolor sit amet,\nconsectetur adipisicing elit,\nsed do eiusmod tempor incididunt',
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   styles: {}
    // },
    // {
    //   type: 'text',
    //   version: '3.6.3',
    //   left: 32,
    //   top: 438,
    //   width: 598.13,
    //   height: 254.93,
    //   fill: '#69C5C5',
    //   scaleX: 0.5,
    //   scaleY: 0.5,
    //   angle: 4,
    //   text: 'Lorem ipsum dolor sit amet,\nconsectetur adipisicing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore magna aliqua.\nUt enim ad mini',
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   styles: {}
    // },
    // {
    //   type: 'rect',
    //   version: '3.6.3',
    //   left: 175,
    //   top: 105,
    //   width: 50,
    //   height: 50,
    //   fill: '#761C05',
    //   opacity: 0.8
    // },
    // {
    //   type: 'circle',
    //   version: '3.6.3',
    //   left: 187,
    //   top: 6,
    //   width: 100,
    //   height: 100,
    //   fill: '#360560',
    //   opacity: 0.8,
    //   radius: 50,
    //   startAngle: 0,
    //   endAngle: 6.283185307179586
    // },
    // {
    //   type: 'triangle',
    //   version: '3.6.3',
    //   left: 284,
    //   top: 390,
    //   width: 50,
    //   height: 50,
    //   fill: '#FE047D',
    //   opacity: 0.8
    // },
    // {
    //   type: 'line',
    //   version: '3.6.3',
    //   left: 290,
    //   top: 434,
    //   width: 150,
    //   height: 100,
    //   stroke: '#AD7CEE',
    //   x1: -75,
    //   x2: 75,
    //   y1: -50,
    //   y2: 50
    // },
    // {
    //   type: 'polygon',
    //   version: '3.6.3',
    //   left: 20,
    //   top: 249,
    //   width: 385,
    //   height: 245,
    //   fill: '#3A41A7',
    //   scaleX: 0.55,
    //   scaleY: 0.55,
    //   points: [{ x: 185, y: 0 },
    //     { x: 250, y: 100 },
    //     { x: 385, y: 170 },
    //     { x: 0, y: 245 }]
    // },
    // {
    //   type: 'textbox',
    //   version: '3.6.3',
    //   left: 269,
    //   top: 27,
    //   width: 300,
    //   height: 153.68,
    //   fill: '#E19E54',
    //   angle: -1,
    //   text: 'Lorem ipsum dolor sit amet,\nconsectetur adipisicing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore magna aliqua.\nUt enim ad minim veniam,\nquis no',
    //   fontSize: 20,
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   minWidth: 20,
    //   splitByGrapheme: false,
    //   styles: {}
    // },
    // {
    //   type: 'i-text',
    //   version: '3.6.3',
    //   left: 391,
    //   top: 296,
    //   width: 493.52,
    //   height: 97.63,
    //   fill: '#D63098',
    //   scaleX: 0.5,
    //   scaleY: 0.5,
    //   angle: -10,
    //   text: 'Lorem ipsum dolor sit amet,\nconsectetur ',
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   styles: {}
    // },
    // {
    //   type: 'text',
    //   version: '3.6.3',
    //   left: 330,
    //   top: 544,
    //   width: 371.25,
    //   height: 45.2,
    //   fill: '#4D690C',
    //   scaleX: 0.5,
    //   scaleY: 0.5,
    //   angle: 5,
    //   text: 'Lorem ipsum dolor si',
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   styles: {}
    // },
    // {
    //   type: 'rect',
    //   version: '3.6.3',
    //   left: 100,
    //   top: 66,
    //   width: 50,
    //   height: 50,
    //   fill: '#1B39BB',
    //   opacity: 0.8
    // },
    // {
    //   type: 'circle',
    //   version: '3.6.3',
    //   left: 266,
    //   top: 98,
    //   width: 100,
    //   height: 100,
    //   fill: '#4F8AF4',
    //   opacity: 0.8,
    //   radius: 50,
    //   startAngle: 0,
    //   endAngle: 6.283185307179586
    // },
    // {
    //   type: 'triangle',
    //   version: '3.6.3',
    //   left: 119,
    //   top: 152,
    //   width: 50,
    //   height: 50,
    //   fill: '#6D16E6',
    //   opacity: 0.8
    // },
    // {
    //   type: 'text',
    //   version: '3.6.3',
    //   left: 365,
    //   top: 237,
    //   width: 493.52,
    //   height: 97.63,
    //   fill: '#44C459',
    //   scaleX: 0.5,
    //   scaleY: 0.5,
    //   angle: -2,
    //   text: 'Lorem ipsum dolor sit amet,\nconsectet',
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   styles: {}
    // },
    // {
    //   type: 'i-text',
    //   version: '3.6.3',
    //   left: 220.87,
    //   top: 288.28,
    //   width: 598.13,
    //   height: 202.5,
    //   fill: '#42CF3F',
    //   scaleX: 0.5,
    //   scaleY: 0.5,
    //   angle: 12.72,
    //   text: 'Lorem ipsum dolor sit amet,\nconsectetur adipisicing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore magna al',
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   styles: {}
    // },
    // {
    //   type: 'circle',
    //   version: '3.6.3',
    //   left: 0,
    //   top: 127,
    //   width: 100,
    //   height: 100,
    //   fill: '#9E4B3C',
    //   opacity: 0.8,
    //   radius: 50,
    //   startAngle: 0,
    //   endAngle: 6.283185307179586
    // },
    // {
    //   type: 'rect',
    //   version: '3.6.3',
    //   left: 530,
    //   top: 16,
    //   width: 50,
    //   height: 50,
    //   fill: '#A209E7',
    //   opacity: 0.8
    // },
    // {
    //   type: 'triangle',
    //   version: '3.6.3',
    //   left: 88,
    //   top: 211,
    //   width: 50,
    //   height: 50,
    //   fill: '#20286E',
    //   opacity: 0.8
    // },
    // {
    //   type: 'line',
    //   version: '3.6.3',
    //   left: 27,
    //   top: 237,
    //   width: 150,
    //   height: 100,
    //   stroke: '#5E9FB3',
    //   x1: -75,
    //   x2: 75,
    //   y1: -50,
    //   y2: 50
    // },
    // {
    //   type: 'circle',
    //   version: '3.6.3',
    //   left: 371,
    //   top: 447,
    //   width: 100,
    //   height: 100,
    //   fill: '#5EC5BA',
    //   opacity: 0.8,
    //   radius: 50,
    //   startAngle: 0,
    //   endAngle: 6.283185307179586
    // },
    // {
    //   type: 'i-text',
    //   version: '3.6.3',
    //   left: 376,
    //   top: 444,
    //   width: 493.52,
    //   height: 150.06,
    //   fill: '#ECB2CC',
    //   scaleX: 0.5,
    //   scaleY: 0.5,
    //   angle: -1,
    //   text: 'Lorem ipsum dolor sit amet,\nconsectetur adipisicing elit,\nsed do ei',
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   styles: {}
    // },
    // {
    //   type: 'rect',
    //   version: '3.6.3',
    //   left: 492,
    //   top: 505,
    //   width: 50,
    //   height: 50,
    //   fill: '#9FA139',
    //   opacity: 0.8
    // },
    // {
    //   type: 'triangle',
    //   version: '3.6.3',
    //   left: 559,
    //   top: 527,
    //   width: 50,
    //   height: 50,
    //   fill: '#D5EB95',
    //   opacity: 0.8
    // },
    // {
    //   type: 'triangle',
    //   version: '3.6.3',
    //   left: 566,
    //   top: 90,
    //   width: 50,
    //   height: 50,
    //   fill: '#D3D188',
    //   opacity: 0.8
    // },
    // {
    //   type: 'polygon',
    //   version: '3.6.3',
    //   left: 834.66,
    //   top: 241.24,
    //   width: 385,
    //   height: 245,
    //   fill: '#9580BF',
    //   scaleX: 0.68,
    //   scaleY: 0.68,
    //   angle: 140,
    //   points: [{ x: 185, y: 0 },
    //     { x: 250, y: 100 },
    //     { x: 385, y: 170 },
    //     { x: 0, y: 245 }]
    // },
    // {
    //   type: 'rect',
    //   version: '3.6.3',
    //   left: 643,
    //   top: 16,
    //   width: 50,
    //   height: 50,
    //   fill: '#C1B138',
    //   scaleX: 2.64,
    //   scaleY: 2.64,
    //   opacity: 0.8
    // },
    // {
    //   type: 'text',
    //   version: '3.6.3',
    //   left: 389,
    //   top: 360,
    //   width: 22.25,
    //   height: 45.2,
    //   fill: '#D6A02D',
    //   scaleX: 0.5,
    //   scaleY: 0.5,
    //   text: 'L',
    //   fontWeight: '',
    //   fontFamily: 'helvetica',
    //   styles: {}
    // },
    // {
    //   type: 'triangle',
    //   version: '3.6.3',
    //   left: 625,
    //   top: 350,
    //   width: 50,
    //   height: 50,
    //   fill: '#908F9F',
    //   opacity: 0.8
    // },
    // {
    //   type: 'circle',
    //   version: '3.6.3',
    //   left: 603,
    //   top: 454,
    //   width: 100,
    //   height: 100,
    //   fill: '#578B25',
    //   opacity: 0.8,
    //   radius: 50,
    //   startAngle: 0,
    //   endAngle: 6.283185307179586
    // },
    // {
    //   type: 'circle',
    //   version: '3.6.3',
    //   left: 681,
    //   top: 388,
    //   width: 100,
    //   height: 100,
    //   fill: '#990621',
    //   opacity: 0.8,
    //   radius: 50,
    //   startAngle: 0,
    //   endAngle: 6.283185307179586
    // },
    // {
    //   type: 'circle',
    //   version: '3.6.3',
    //   left: 676,
    //   top: 491,
    //   width: 100,
    //   height: 100,
    //   fill: '#C2D944',
    //   opacity: 0.8,
    //   radius: 50,
    //   startAngle: 0,
    //   endAngle: 6.283185307179586
    // },
    // {
    //   type: 'circle',
    //   version: '3.6.3',
    //   left: 644,
    //   top: 53,
    //   width: 100,
    //   height: 100,
    //   fill: '#C1532E',
    //   opacity: 0.8,
    //   radius: 50,
    //   startAngle: 0,
    //   endAngle: 6.283185307179586
    // },
    // {
    //   type: 'triangle',
    //   version: '3.6.3',
    //   left: 601,
    //   top: 434,
    //   width: 50,
    //   height: 50,
    //   fill: '#54CD04',
    //   opacity: 0.8
    // },
    // {
    //   type: 'line',
    //   version: '3.6.3',
    //   left: 435,
    //   top: 198,
    //   width: 150,
    //   height: 100,
    //   stroke: '#D08D13',
    //   x1: -75,
    //   x2: 75,
    //   y1: -50,
    //   y2: 50
    // },
    // {
    //   type: 'rect',
    //   version: '3.6.3',
    //   left: 101,
    //   top: 12,
    //   width: 50,
    //   height: 50,
    //   fill: '#7A7D9C',
    //   opacity: 0.8
    // },
    // {
    //   type: 'rect',
    //   version: '3.6.3',
    //   left: 14,
    //   top: 7,
    //   width: 50,
    //   height: 50,
    //   fill: '#16C0EF',
    //   opacity: 0.8
    // },
    // {
    //   type: 'rect',
    //   version: '3.6.3',
    //   left: 22,
    //   top: 74.17,
    //   width: 50,
    //   height: 50,
    //   fill: '#8A4CDE',
    //   angle: 355.3,
    //   opacity: 0.8
    // }
  ]
}
